export const ADD_TODO = 'todo/add'
export const DELETE_TODO = 'todo/delete'
export const TOGGLE_TODO = 'todo/toggle'
export const COMPLETE_ALL = 'todo/complete/all'
export const UPDATE_COLOR = 'todo/status/update'
export const REMOVE_ALL_COMPLETE = 'todo/complete/remove'
export const FILTER_TODO = 'todo/complete/remove'
